# Generated by Django 2.0.1 on 2018-02-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_fen', models.CharField(max_length=100, unique=True)),
                ('move_played', models.CharField(max_length=10)),
                ('best_move_san', models.CharField(max_length=10)),
                ('best_move_uci', models.CharField(max_length=10)),
                ('game_url', models.URLField()),
            ],
        ),
    ]
