# Generated by Django 2.0.1 on 2018-02-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180203_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_url',
            field=models.URLField(blank=True),
        ),
    ]
